"""
LockWorks v7.0: Echo Chamber Test
==================================

Compares baseline (v6.4) vs Echo-enhanced circuit.

Hypothesis: Echo will reduce baseline syndrome from ~5% to <1%
by cancelling phase drift generated during the X-Link gearing.
"""

import sys
import os
import json
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from src.echo_chamber import EchoChamber
from src.needle import NeedleDriver


class WitnessV7:
    """
    LockWorks v7.0: Echo Chamber Witness.
    
    Extends the v6.4 pattern with a Hahn Echo between Link and Braid.
    """
    
    def __init__(self, complexity: int = 6):
        self.complexity = complexity
        self.q = QuantumRegister(6, 'q')
        self.c = ClassicalRegister(3, 'meas')
        self.data_indices = [1, 3, 5]
    
    def build_baseline_circuit(self, val_a: int, val_b: int) -> QuantumCircuit:
        """
        Build v6.4-style baseline circuit (no echo).
        """
        qc = QuantumCircuit(self.q, self.c)
        
        # 1. OPEN
        qc.h(self.q)
        
        # 2. X-LINK
        qc.barrier()
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.cx(self.q[5], self.q[1])
        qc.cx(self.q[5], self.q[3])
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.barrier()
        
        # 3. BRAID
        self._braid(qc, 0, val_a)
        self._braid(qc, 1, val_b)
        self._braid(qc, 2, 0)
        
        # 4. MEASURE (X-Basis)
        qc.barrier()
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.measure(self.q[1], self.c[0])
        qc.measure(self.q[3], self.c[1])
        qc.measure(self.q[5], self.c[2])
        
        return qc
    
    def build_echo_circuit(self, val_a: int, val_b: int, delay: int = 5) -> QuantumCircuit:
        """
        Build v7.0 Echo Chamber circuit.
        
        Sequence: OPEN -> X-LINK -> ECHO -> BRAID -> MEASURE
        """
        qc = QuantumCircuit(self.q, self.c)
        
        # 1. OPEN
        qc.h(self.q)
        
        # 2. X-LINK
        qc.barrier()
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.cx(self.q[5], self.q[1])
        qc.cx(self.q[5], self.q[3])
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.barrier()
        
        # === 3. THE ECHO CHAMBER (v7.0) ===
        # Scrub the phase drift generated by the Link
        data_qubits = [self.q[1], self.q[3], self.q[5]]
        EchoChamber.apply_echo(qc, data_qubits, delay_cycles=delay)
        
        # 4. BRAID
        self._braid(qc, 0, val_a)
        self._braid(qc, 1, val_b)
        self._braid(qc, 2, 0)
        
        # 5. MEASURE (X-Basis)
        qc.barrier()
        for idx in self.data_indices:
            qc.h(self.q[idx])
        qc.measure(self.q[1], self.c[0])
        qc.measure(self.q[3], self.c[1])
        qc.measure(self.q[5], self.c[2])
        
        return qc
    
    def _braid(self, qc: QuantumCircuit, idx: int, val: int) -> None:
        theta = 0.196 if val == 1 else 0.0
        p = idx * 2
        d = idx * 2 + 1
        
        for _ in range(self.complexity):
            qc.cz(self.q[p], self.q[d])
            qc.rx(theta, self.q[p])
            qc.rz(theta * 2, self.q[d])
            qc.barrier([self.q[p], self.q[d]])


def calculate_syndrome(counts: dict) -> float:
    """Calculate X-parity syndrome."""
    total = sum(counts.values())
    mismatch = 0
    for state, count in counts.items():
        bits = [int(b) for b in state.zfill(3)]
        if bits[0] != (bits[1] ^ bits[2]):
            mismatch += count
    return mismatch / total if total > 0 else 0


def run_echo_test():
    print("=" * 70)
    print("    LOCKWORKS v7.0: ECHO CHAMBER TEST")
    print("    Phase Drift Cancellation")
    print("=" * 70)
    
    needle = NeedleDriver()
    witness = WitnessV7(complexity=6)
    
    val_a, val_b = 0, 0  # ROBUST poles
    
    results = []
    
    # 1. Baseline (v6.4 style - no echo)
    print("\n📍 Running Baseline (v6.4 style)...")
    qc_base = witness.build_baseline_circuit(val_a, val_b)
    res_base = needle.read_circuit(qc_base)
    syn_base = calculate_syndrome(res_base.raw_counts)
    results.append({
        "mode": "BASELINE",
        "syndrome": syn_base,
        "counts": res_base.raw_counts
    })
    print(f"   Baseline Syndrome: {syn_base:.2%}")
    
    # 2. Echo (v7.0)
    print("\n📍 Running Echo Chamber (v7.0)...")
    qc_echo = witness.build_echo_circuit(val_a, val_b, delay=5)
    res_echo = needle.read_circuit(qc_echo)
    syn_echo = calculate_syndrome(res_echo.raw_counts)
    results.append({
        "mode": "ECHO",
        "syndrome": syn_echo,
        "counts": res_echo.raw_counts
    })
    print(f"   Echo Syndrome:     {syn_echo:.2%}")
    
    # Analysis
    print("\n" + "=" * 70)
    print("    ECHO CHAMBER ANALYSIS")
    print("=" * 70)
    
    improvement = syn_base - syn_echo
    reduction_pct = (improvement / syn_base * 100) if syn_base > 0 else 0
    
    print(f"\n   Baseline Syndrome: {syn_base:.2%}")
    print(f"   Echo Syndrome:     {syn_echo:.2%}")
    print(f"   Drift Reduction:   {improvement:+.2%} ({reduction_pct:.1f}% improvement)")
    
    # Verdict
    print("\n" + "=" * 70)
    
    if syn_echo < 0.01:
        print("🏆 ULTRA-CLEAN: Syndrome < 1%!")
        print("   The signal is pristine. Hardware noise floor achieved.")
    elif syn_echo < 0.02:
        print("🏆 ECHO SUCCESS: Syndrome < 2%!")
        print("   The signal is clean.")
    elif syn_echo < syn_base * 0.5:
        print("✅ STRONG IMPROVEMENT: >50% reduction!")
        print(f"   Syndrome reduced by {reduction_pct:.1f}%")
    elif syn_echo < syn_base:
        print("📈 PARTIAL SUCCESS: Syndrome reduced.")
        print(f"   Improvement: {reduction_pct:.1f}%")
    else:
        print("📊 NO IMPROVEMENT: Echo may have added noise.")
        print("   Consider adjusting delay_cycles or using CPMG.")
    
    print("=" * 70)
    
    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"lockworks_v7_0_echo_{timestamp}.json"
    
    with open(filename, 'w') as f:
        json.dump({
            "timestamp": timestamp,
            "experiment": "echo_chamber",
            "version": "7.0",
            "test_case": {"val_a": val_a, "val_b": val_b},
            "results": results,
            "metrics": {
                "syndrome_baseline": syn_base,
                "syndrome_echo": syn_echo,
                "drift_reduction": improvement,
                "reduction_percent": reduction_pct
            }
        }, f, indent=2, default=str)
    
    print(f"\n💾 Saved: {filename}")
    
    return results


if __name__ == "__main__":
    run_echo_test()
